# Generated by Django 6.0.6 on 2026-06-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in Featured Products section'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_rotation',
            field=models.BooleanField(default=False, help_text='Show in Product Wheel / Rotation section'),
        ),
    ]
